// DermNet contact allergens — https://dermnetnz.org/topics/contact-allergens
export interface KnownAllergen {
  name: string
  aliases: string[]
  category: string
  severity: "high" | "medium" | "low"
  description: string
}

export const ALLERGEN_DB: KnownAllergen[] = [
  { name: "acrylates", aliases: ["acrylate", "methacrylate", "ethyl acrylate", "methyl methacrylate", "hydroxyethyl methacrylate", "hema"], category: "chemical", severity: "high", description: "Found in nail products, dental materials, and adhesives. A major cause of occupational contact dermatitis for nail technicians." },
  { name: "ammonium persulfate", aliases: ["ammonium persulphate", "persulfate", "persulphate"], category: "chemical", severity: "high", description: "Bleaching agent used in hair lightening products. Can cause contact urticaria, asthma, and anaphylaxis in hairdressers." },
  { name: "avobenzone", aliases: ["avobenzone", "butyl methoxydibenzoylmethane", "parsol 1789"], category: "uv_filter", severity: "medium", description: "UV-A filter in sunscreens. Can cause photocontact dermatitis." },
  { name: "bacitracin", aliases: ["bacitracin", "bacitracin zinc"], category: "topical_drug", severity: "high", description: "Topical antibiotic in first-aid ointments. A significant contact allergen, often co-reacting with neomycin." },
  { name: "balsam of peru", aliases: ["balsam of peru", "myroxylon pereirae", "peru balsam", "myroxylon balsamum"], category: "botanical", severity: "high", description: "A natural resin used in fragrances and flavourings. One of the most common patch test allergens. Cross-reacts with fragrances, cinnamon, and propolis." },
  { name: "benzalkonium chloride", aliases: ["benzalkonium chloride", "bac", "alkyl dimethyl benzyl ammonium chloride"], category: "preservative", severity: "medium", description: "Quaternary ammonium antimicrobial used in eye drops, disinfectants, and some cosmetics." },
  { name: "benzisothiazolinone", aliases: ["benzisothiazolinone", "bit", "1,2-benzisothiazol-3(2h)-one"], category: "preservative", severity: "medium", description: "Preservative used in household products, paints, and some cosmetics. Related to methylisothiazolinone." },
  { name: "benzocaine", aliases: ["benzocaine", "ethyl aminobenzoate"], category: "topical_drug", severity: "high", description: "Topical local anaesthetic. One of the most common causes of contact allergy to topical medications. Cross-reacts with PPD." },
  { name: "benzophenone", aliases: ["benzophenone", "benzophenone-3", "oxybenzone", "benzophenone-4", "sulisobenzone"], category: "uv_filter", severity: "high", description: "UV filter and photoinitiator. A well-known photoallergen causing photocontact dermatitis. Found in sunscreens, nail polish, and plastics." },
  { name: "bemotrizinol", aliases: ["bemotrizinol", "tinosorb s", "bis-ethylhexyloxyphenol methoxyphenyl triazine"], category: "uv_filter", severity: "low", description: "Broad-spectrum UV filter used in European sunscreens. Rare contact allergen." },
  { name: "bisoctrizole", aliases: ["bisoctrizole", "tinosorb m", "methylene bis-benzotriazolyl tetramethylbutylphenol"], category: "uv_filter", severity: "low", description: "Broad-spectrum UV filter. Rare contact allergen found in some sunscreens." },
  { name: "chrome", aliases: ["chrome", "chromium", "chromate", "potassium dichromate", "chromium vi", "hexavalent chromium"], category: "metal", severity: "high", description: "Found in cement, leather, and some green cosmetic pigments. Chromium VI is the allergenic form causing chronic hand dermatitis." },
  { name: "cinnamate", aliases: ["cinnamate", "cinnamaldehyde", "cinnamic alcohol", "cinnamyl alcohol", "cinnamic acid", "octinoxate", "ethylhexyl methoxycinnamate"], category: "fragrance", severity: "high", description: "Fragrance component and UV filter. Found in fragrances, cinnamon, and sunscreens (octinoxate). EU-listed fragrance allergen." },
  { name: "clioquinol", aliases: ["clioquinol", "iodochlorhydroxyquin", "vioform"], category: "topical_drug", severity: "medium", description: "Antiseptic used in some topical medications. Can cause contact dermatitis and cross-reacts with other halogenated hydroxyquinolines." },
  { name: "cobalt", aliases: ["cobalt", "cobalt chloride", "cobalt sulfate", "cobalt blue"], category: "metal", severity: "medium", description: "Found in metal alloys, pigments, and vitamin B12. Often co-sensitised with nickel. Causes contact dermatitis." },
  { name: "cocamidopropyl betaine", aliases: ["cocamidopropyl betaine", "capb", "cocamidopropyl dimethyl glycine"], category: "surfactant", severity: "medium", description: "Common surfactant in shampoos and cleansers. Despite its 'mild' reputation, a recognised contact allergen, especially from impurities." },
  { name: "coconut diethanolamide", aliases: ["coconut diethanolamide", "cocamide dea", "cocamide mea"], category: "surfactant", severity: "medium", description: "Foam-boosting agent in shampoos. Can cause allergic contact dermatitis. DEA compounds may form nitrosamines." },
  { name: "colophony", aliases: ["colophony", "rosin", "pine resin", "abietic acid", "hydrogenated rosin", "tall oil rosin"], category: "botanical", severity: "medium", description: "Pine-derived resin found in adhesives, mascaras, waxes, and some topical products. Common patch test allergen." },
  { name: "compositae", aliases: ["compositae", "asteraceae", "chrysanthemum", "arnica", "chamomile", "echinacea", "feverfew", "yarrow", "sesquiterpene lactone"], category: "botanical", severity: "medium", description: "Plant family including chamomile, arnica, and echinacea. Sesquiterpene lactones are the allergenic components found in many 'natural' cosmetics." },
  { name: "diethylthiourea", aliases: ["diethylthiourea", "detu"], category: "rubber_chemical", severity: "medium", description: "Rubber accelerator used in neoprene products such as wetsuits and some gloves." },
  { name: "dimethyl fumarate", aliases: ["dimethyl fumarate", "dmf"], category: "chemical", severity: "high", description: "Anti-mould agent formerly used in furniture sachets. Caused a major outbreak of severe contact dermatitis across Europe." },
  { name: "ecamsule", aliases: ["ecamsule", "mexoryl sx", "terephthalylidene dicamphor sulfonic acid"], category: "uv_filter", severity: "low", description: "UV filter used in some sunscreens. Rare contact allergen." },
  { name: "ensulizole", aliases: ["ensulizole", "phenylbenzimidazole sulfonic acid", "parsol hs"], category: "uv_filter", severity: "low", description: "Water-soluble UV-B filter. Rare photocontact allergen." },
  { name: "epoxy resin", aliases: ["epoxy resin", "bisphenol a epoxy", "bisphenol f epoxy", "diglycidyl ether of bisphenol a", "dgeba"], category: "chemical", severity: "high", description: "Used in adhesives, coatings, and dental materials. Uncured epoxy resin is a potent sensitiser causing occupational contact dermatitis." },
  { name: "essential oils", aliases: ["essential oil", "tea tree oil", "lavender oil", "peppermint oil", "eucalyptus oil", "ylang ylang", "clove oil", "rosemary oil"], category: "botanical", severity: "high", description: "Natural volatile plant extracts used in aromatherapy and cosmetics. Despite being 'natural', many are significant contact allergens." },
  { name: "ethylenediamine", aliases: ["ethylenediamine", "1,2-diaminoethane"], category: "chemical", severity: "medium", description: "Used as a stabiliser in some topical creams and industrial products. Cross-reacts with antihistamines and aminophylline." },
  { name: "formaldehyde", aliases: ["formaldehyde", "formalin", "methanal", "dmdm hydantoin", "imidazolidinyl urea", "diazolidinyl urea", "quaternium-15", "bronopol", "glyoxal", "sodium hydroxymethylglycinate"], category: "preservative", severity: "high", description: "A preservative and formaldehyde-releasing preservatives are widespread in cosmetics. Known sensitiser and carcinogen. Formaldehyde releasers are common hidden sources." },
  { name: "fragrance mix", aliases: ["fragrance", "parfum", "perfume", "aroma", "fragrance mix i", "fragrance mix ii", "linalool", "limonene", "eugenol", "geraniol", "isoeugenol", "cinnamal", "hydroxycitronellal", "coumarin", "farnesol"], category: "fragrance", severity: "high", description: "The #1 cause of allergic contact dermatitis in cosmetics. 'Fragrance' on a label can conceal dozens of sensitising chemicals including EU-listed allergens." },
  { name: "glyceryl thioglycolate", aliases: ["glyceryl thioglycolate", "glyceryl monothioglycolate", "thioglycolate", "acid perm solution"], category: "chemical", severity: "high", description: "Active ingredient in acid perming solutions for hair. Causes occupational contact dermatitis in hairdressers." },
  { name: "gold", aliases: ["gold", "gold sodium thiosulfate", "gold chloride", "auric chloride"], category: "metal", severity: "medium", description: "Jewellery and dental alloys. Gold is a common contact allergen — positive patch tests are frequent though clinical relevance varies." },
  { name: "imidazolidinyl urea", aliases: ["imidazolidinyl urea", "germall 115", "germaben"], category: "preservative", severity: "medium", description: "A formaldehyde-releasing preservative used in cosmetics and personal care products." },
  { name: "iodopropynyl butylcarbamate", aliases: ["iodopropynyl butylcarbamate", "ipbc", "isopropynyl butylcarbamate"], category: "preservative", severity: "medium", description: "Antifungal preservative used in cosmetics and household products. Can cause contact dermatitis." },
  { name: "isothiazolinone", aliases: ["methylisothiazolinone", "mit", "methylchloroisothiazolinone", "mci", "kathon cg", "octylisothiazolinone", "oit", "benzisothiazolinone"], category: "preservative", severity: "high", description: "A family of biocide preservatives. Among the most prevalent contact allergens currently. Banned or restricted in leave-on cosmetics in the EU." },
  { name: "lanolin", aliases: ["lanolin", "wool alcohols", "wool wax", "wool fat", "anhydrous lanolin", "lanolin alcohol", "acetylated lanolin"], category: "emollient", severity: "medium", description: "Emollient derived from sheep wool. Lanolin alcohol is a well-documented contact allergen, especially in medicinal creams and lip products." },
  { name: "latex", aliases: ["latex", "natural rubber", "rubber latex", "hevea brasiliensis", "natural rubber latex"], category: "rubber_chemical", severity: "high", description: "Natural rubber latex proteins in gloves, bandages, and elastic. Causes Type I (immediate) hypersensitivity including anaphylaxis." },
  { name: "lauryl glucoside", aliases: ["lauryl glucoside", "decyl glucoside", "coco glucoside", "alkyl glucoside"], category: "surfactant", severity: "medium", description: "Sugar-derived surfactants marketed as 'natural' and 'mild'. Increasingly recognised as contact allergens, especially in baby and sensitive-skin products." },
  { name: "methyldibromo glutaronitrile", aliases: ["methyldibromo glutaronitrile", "mdgn", "dibromodicyanobutane", "euxyl k400"], category: "preservative", severity: "high", description: "A preservative banned in leave-on cosmetics in the EU due to high sensitisation rates. Still found in some rinse-off products." },
  { name: "neomycin", aliases: ["neomycin", "neomycin sulfate", "neosporin", "framycetin"], category: "topical_drug", severity: "high", description: "Topical antibiotic in wound care products. One of the most common topical drug allergens. Cross-reacts with other aminoglycosides." },
  { name: "nickel", aliases: ["nickel", "nickel sulfate", "nickel chloride"], category: "metal", severity: "high", description: "The most common contact allergen globally. Found in jewellery, belt buckles, coins, and trace amounts in some cosmetics." },
  { name: "octyl glucoside", aliases: ["octyl glucoside", "1-o-octyl-beta-d-glucopyranoside"], category: "surfactant", severity: "medium", description: "A mild non-ionic surfactant. Emerging contact allergen in some 'natural' personal care products." },
  { name: "paba", aliases: ["paba", "para-aminobenzoic acid", "aminobenzoic acid", "padimate o", "ethylhexyl dimethyl paba"], category: "uv_filter", severity: "high", description: "One of the earliest UV filters. A potent photoallergen — largely phased out of modern sunscreens but still in some older formulations." },
  { name: "paraben mix", aliases: ["paraben", "methylparaben", "ethylparaben", "propylparaben", "butylparaben", "isobutylparaben", "isopropylparaben", "benzylparaben"], category: "preservative", severity: "medium", description: "Widely used preservative family in cosmetics. Can cause contact dermatitis, particularly methylparaben. Cross-reactivity between parabens is common." },
  { name: "paraphenylenediamine", aliases: ["ppd", "paraphenylenediamine", "p-phenylenediamine", "4-phenylenediamine", "ursol d", "hair dye"], category: "colorant", severity: "high", description: "The primary oxidative dye in permanent hair colours. The most common cause of severe allergic contact dermatitis from cosmetics. Can cause anaphylaxis. Cross-reacts with benzocaine and sulfonamides." },
  { name: "propolis", aliases: ["propolis", "bee propolis", "bee glue", "bee resin"], category: "botanical", severity: "medium", description: "A bee-collected resin used in 'natural' skincare and wound products. Contact allergen cross-reactive with balsam of Peru and fragrances." },
  { name: "propylene glycol", aliases: ["propylene glycol", "1,2-propanediol", "propane-1,2-diol"], category: "solvent", severity: "low", description: "Humectant and solvent used widely in cosmetics and pharmaceuticals. Contact allergen at higher concentrations, especially under occlusion." },
  { name: "ptbp formaldehyde resin", aliases: ["ptbp resin", "p-tert-butylphenol formaldehyde resin", "para-tertiary-butylphenol formaldehyde resin"], category: "chemical", severity: "high", description: "Resin used in adhesives, leather goods, and shoes. A cause of shoe contact dermatitis and depigmentation (chemical leukoderma)." },
  { name: "quaternium-15", aliases: ["quaternium-15", "dowicil 200"], category: "preservative", severity: "high", description: "A formaldehyde-releasing preservative. One of the most common preservative allergens in North America." },
  { name: "rubber accelerators", aliases: ["thiuram", "thiuram mix", "mercapto mix", "mercaptobenzothiazole", "mbt", "carba mix", "thiourea", "dithiocarbamate", "ppt", "dptu"], category: "rubber_chemical", severity: "high", description: "Chemical accelerators used in rubber manufacture. Found in gloves, condoms, footwear, and elastic bands. Common cause of glove-related contact dermatitis." },
  { name: "salicylate", aliases: ["salicylate", "salicylic acid", "sodium salicylate", "methyl salicylate", "topical salicylate", "aspirin"], category: "topical_drug", severity: "medium", description: "Used in topical analgesics and anti-acne products. Contact allergy is uncommon but can occur. Cross-reacts with aspirin in some individuals." },
  { name: "shellac", aliases: ["shellac", "lac resin", "pharmaceutical glaze", "confectioner's glaze"], category: "botanical", severity: "medium", description: "Resin secreted by lac bugs. Used in nail products, hair sprays, and tablet coatings. Can cause contact dermatitis." },
  { name: "sodium metabisulphite", aliases: ["sodium metabisulphite", "sodium metabisulfite", "sodium bisulphite", "potassium metabisulphite", "sulphite", "sulfite", "e223", "e224"], category: "preservative", severity: "medium", description: "Preservative and antioxidant used in cosmetics, topical medications, and food. Can cause contact urticaria and asthma." },
  { name: "textile dyes", aliases: ["disperse blue", "disperse yellow", "disperse orange", "disperse red", "azo dye", "textile dye"], category: "colorant", severity: "medium", description: "Synthetic dyes used in polyester and nylon fabrics. Disperse dyes are the main culprits in textile contact dermatitis, especially from sportswear." },
  { name: "thiomersal", aliases: ["thiomersal", "thimerosal", "sodium ethylmercurithiosalicylate"], category: "preservative", severity: "medium", description: "Mercury-based preservative formerly in contact lens solutions and some vaccines. A common patch test allergen, though largely phased out." },
  { name: "topical corticosteroids", aliases: ["hydrocortisone", "betamethasone", "triamcinolone", "mometasone", "clobetasol", "fluocinolone", "desoximetasone", "budesonide", "tixocortol pivalate"], category: "topical_drug", severity: "medium", description: "Anti-inflammatory steroids used for skin conditions. Paradoxically can cause allergic contact dermatitis. Grouped into classes A–D for cross-reactivity." },
  { name: "wool alcohols", aliases: ["wool alcohols", "lanolin", "lanolin alcohol", "wool wax alcohol"], category: "emollient", severity: "medium", description: "The allergen fraction of lanolin. Found in moisturisers, ointments, and lip products. See also: lanolin." },
]

// Simple lookup
export function lookupAllergen(token: string): KnownAllergen | null {
  const lower = token.toLowerCase()
  for (const a of ALLERGEN_DB) {
    if (lower.includes(a.name) || a.name.includes(lower)) return a
    for (const alias of a.aliases) {
      if (lower.includes(alias) || alias.includes(lower)) return a
    }
  }
  return null
}

// All names + aliases for autocomplete
export const ALL_ALLERGEN_ALIASES: string[] = ALLERGEN_DB.flatMap(a => [a.name, ...a.aliases])
